/*
Copyright 2019 The Knative Authors
Copyright 2019 Scott Nichols

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/n3wscott/rssfeed/pkg/apis/sources/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRssFeeds implements RssFeedInterface
type FakeRssFeeds struct {
	Fake *FakeSourcesV1alpha1
	ns   string
}

var rssfeedsResource = schema.GroupVersionResource{Group: "sources.n3wscott.com", Version: "v1alpha1", Resource: "rssfeeds"}

var rssfeedsKind = schema.GroupVersionKind{Group: "sources.n3wscott.com", Version: "v1alpha1", Kind: "RssFeed"}

// Get takes name of the rssFeed, and returns the corresponding rssFeed object, and an error if there is any.
func (c *FakeRssFeeds) Get(name string, options v1.GetOptions) (result *v1alpha1.RssFeed, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(rssfeedsResource, c.ns, name), &v1alpha1.RssFeed{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RssFeed), err
}

// List takes label and field selectors, and returns the list of RssFeeds that match those selectors.
func (c *FakeRssFeeds) List(opts v1.ListOptions) (result *v1alpha1.RssFeedList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(rssfeedsResource, rssfeedsKind, c.ns, opts), &v1alpha1.RssFeedList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RssFeedList{ListMeta: obj.(*v1alpha1.RssFeedList).ListMeta}
	for _, item := range obj.(*v1alpha1.RssFeedList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested rssFeeds.
func (c *FakeRssFeeds) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(rssfeedsResource, c.ns, opts))

}

// Create takes the representation of a rssFeed and creates it.  Returns the server's representation of the rssFeed, and an error, if there is any.
func (c *FakeRssFeeds) Create(rssFeed *v1alpha1.RssFeed) (result *v1alpha1.RssFeed, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(rssfeedsResource, c.ns, rssFeed), &v1alpha1.RssFeed{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RssFeed), err
}

// Update takes the representation of a rssFeed and updates it. Returns the server's representation of the rssFeed, and an error, if there is any.
func (c *FakeRssFeeds) Update(rssFeed *v1alpha1.RssFeed) (result *v1alpha1.RssFeed, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(rssfeedsResource, c.ns, rssFeed), &v1alpha1.RssFeed{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RssFeed), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRssFeeds) UpdateStatus(rssFeed *v1alpha1.RssFeed) (*v1alpha1.RssFeed, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(rssfeedsResource, "status", c.ns, rssFeed), &v1alpha1.RssFeed{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RssFeed), err
}

// Delete takes name of the rssFeed and deletes it. Returns an error if one occurs.
func (c *FakeRssFeeds) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(rssfeedsResource, c.ns, name), &v1alpha1.RssFeed{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRssFeeds) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(rssfeedsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.RssFeedList{})
	return err
}

// Patch applies the patch and returns the patched rssFeed.
func (c *FakeRssFeeds) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RssFeed, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rssfeedsResource, c.ns, name, data, subresources...), &v1alpha1.RssFeed{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RssFeed), err
}
